// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportFrameAsPNG(arg1, arg2) {
  return window['go']['main']['App']['ExportFrameAsPNG'](arg1, arg2);
}

export function ExportSpriteDataJSON(arg1) {
  return window['go']['main']['App']['ExportSpriteDataJSON'](arg1);
}

export function ExportSpriteDataRON(arg1) {
  return window['go']['main']['App']['ExportSpriteDataRON'](arg1);
}

export function GenerateSampleSpriteSheet() {
  return window['go']['main']['App']['GenerateSampleSpriteSheet']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function ImportImageAsProject() {
  return window['go']['main']['App']['ImportImageAsProject']();
}

export function ImportImageToFrame(arg1) {
  return window['go']['main']['App']['ImportImageToFrame'](arg1);
}

export function ImportSpriteData(arg1) {
  return window['go']['main']['App']['ImportSpriteData'](arg1);
}

export function LoadSpriteSheet() {
  return window['go']['main']['App']['LoadSpriteSheet']();
}

export function PackFramesToSheet(arg1) {
  return window['go']['main']['App']['PackFramesToSheet'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}
