// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CreateProject(arg1:string,arg2:number):Promise<models.Project>;

export function DeleteProject(arg1:number):Promise<boolean>;

export function ExportFrameAsPNG(arg1:models.PixelFrame,arg2:number):Promise<string>;

export function GenerateSampleSpriteSheet():Promise<models.PixelFrame>;

export function GetProjects():Promise<Array<models.Project>>;

export function ImportImageAsProject():Promise<models.Project>;

export function ImportImageToFrame(arg1:number):Promise<models.PixelFrame>;

export function LoadSpriteSheet():Promise<models.PixelFrame>;

export function PackFramesToSheet(arg1:models.Project):Promise<main.PackResult>;

export function SaveProject(arg1:models.Project):Promise<void>;
